use latest seleniarm docker image
ddev/ddev-selenium-standalone-chrome pull request #31
Opened 2023-10-10 18:55 UTC by byrond

## The Issue

The Docker Composer file is pinned against a really old version of the seleniarm image.

## How This PR Solves The Issue

Updates the tag for the image to `latest`, and users can pin to a specific version if desired.

## Manual Testing Instructions

Update `docker-compose.selenium-chrome.yaml` in an existing project to use the `latest` tag and run `ddev poweroff && ddev start`

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-10-10 19:40 UTC, rfay requested changes
Using the movable tag `latest` is usually a bad idea, because upstream changes can just result in disaster for no reason. Instead, if 117.0 works (currently the same as current `latest`), why not use that? You can test it locally to see.

2023-10-11 13:21 UTC, weitzman commented
Code looks good. Unclear to me what is the cause of the test failure - https://github.com/ddev/ddev-selenium-standalone-chrome/actions/runs/6483056158/job/17603806583?pr=31#step:12:465

2023-10-11 13:30 UTC, byrond commented
Maybe it's pickier about YAML now? Trying quotes around the image tag.

2023-10-11 13:49 UTC, rfay commented
> 117.0 seems to be a movable tag as well. Should it be something like [117.0-chromedriver-117.0-grid-4.10.0-20230926](https://hub.docker.com/layers/seleniarm/standalone-chromium/117.0-chromedriver-117.0-grid-4.10.0-20230926/images/sha256-9db388a74042499c6591be5f7c26aa0c36a819c22d21ccd10c61feaf0b919c14?context=explore)?

Usually tags like 117.0 may be updated but will stay with the same basic version of the local stuff. For example, solr:8 stays with solr 8. Or solr:8.8 might stays with solr 8.8*

2023-10-13 00:07 UTC, byrond commented
In local testing, I found that PHPUnit would hang before trying to start a Functional JavaScript test, which I believe is what is happening now on CI. Using noVNC, it appears the browser is not starting at all (with the `--headless` option removed from our driver args).

2023-10-13 14:11 UTC, byrond commented
I'll just close this until we (or someone else) can find an updated `seleniarm` Docker image that works. It would be nice to test with a newer version of Chromium (especially >=112 for the updated `--headless=new` mode), but this does work as-is. I wonder if a simpler image with just Chromium and ChromiumDriver would suffice. It's my understanding that Behat needs to use Chrome directly through the remote debugging port, while PHPUnit needs to access Chrome through a web driver. I believe that is due to differences in how each implements user login steps.

2023-10-13 14:11 UTC, closed without merging